"""add livekit room fields to class_sessions

Revision ID: 2f88a38e6db2
Revises: 8338416754ce
Create Date: 2026-07-15 12:41:24.897857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f88a38e6db2'
down_revision: Union[str, Sequence[str], None] = '8338416754ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('class_sessions', sa.Column('room_name', sa.String(), nullable=True))
    # Add as nullable first so existing rows don't violate NOT NULL
    op.add_column('class_sessions', sa.Column('room_status', sa.String(), nullable=True))
    op.add_column('class_sessions', sa.Column('recording_url', sa.String(), nullable=True))
    op.add_column('class_sessions', sa.Column('recording_status', sa.String(), nullable=True))

    # Backfill existing rows with a default status before enforcing NOT NULL
    op.execute("UPDATE class_sessions SET room_status = 'pending' WHERE room_status IS NULL")

    # Now safe to enforce NOT NULL
    op.alter_column('class_sessions', 'room_status', nullable=False)

    op.create_unique_constraint(None, 'class_sessions', ['room_name'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'class_sessions', type_='unique')
    op.drop_column('class_sessions', 'recording_status')
    op.drop_column('class_sessions', 'recording_url')
    op.drop_column('class_sessions', 'room_status')
    op.drop_column('class_sessions', 'room_name')
    # ### end Alembic commands ###
