"""add started and ended at columns to class_session

Revision ID: 460ebb5c8d86
Revises: be82f05ab14f
Create Date: 2026-06-24 11:20:55.604650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '460ebb5c8d86'
down_revision: Union[str, Sequence[str], None] = 'be82f05ab14f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_sessions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('class_sessions', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('class_sessions', sa.Column('ended_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class_sessions', 'ended_at')
    op.drop_column('class_sessions', 'started_at')
    op.drop_column('class_sessions', 'is_active')
    # ### end Alembic commands ###
