"""create classrooms table

Revision ID: 51eac706df72
Revises: e62843dccff5
Create Date: 2026-06-15 16:03:21.111498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51eac706df72'
down_revision: Union[str, Sequence[str], None] = 'e62843dccff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.drop_constraint('courses_classroom_id_fkey', 'courses', type_='foreignkey')
    op.drop_constraint('students_classroom_id_fkey', 'students', type_='foreignkey')
    op.drop_table('classroom')
    op.create_foreign_key(None, 'courses', 'classrooms', ['classroom_id'], ['id'])
    op.create_foreign_key(None, 'students', 'classrooms', ['classroom_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_classroom_id_fkey'), 'students', 'classroom', ['classroom_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('courses_classroom_id_fkey'), 'courses', 'classroom', ['classroom_id'], ['id'], ondelete='CASCADE')
    op.create_table('classroom',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('section', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('academic_year', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('classroom_pkey'))
    )
    op.drop_table('classrooms')
    # ### end Alembic commands ###
