"""add remember token to user

Revision ID: 99b5908d6a76
Revises: c192c85126f0
Create Date: 2026-06-26 11:55:38.220269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99b5908d6a76'
down_revision: Union[str, Sequence[str], None] = 'c192c85126f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('remember_token', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('remember_token_expiry', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_remember_token'), 'users', ['remember_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_remember_token'), table_name='users')
    op.drop_column('users', 'remember_token_expiry')
    op.drop_column('users', 'remember_token')
    # ### end Alembic commands ###
