"""fix note teacher_id fkey

Revision ID: be82f05ab14f
Revises: 05ccc505481e
Create Date: 2026-06-15 16:59:33.407836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be82f05ab14f'
down_revision: Union[str, Sequence[str], None] = '05ccc505481e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('notes_teacher_id_fkey'), 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key(op.f('notes_teacher_id_fkey'), 'notes', 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
