"""make teacher_id nullable in courses

Revision ID: d8e32a9f241b
Revises: f20dcd7a8084
Create Date: 2026-06-15 16:54:28.001837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e32a9f241b'
down_revision: Union[str, Sequence[str], None] = 'f20dcd7a8084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
